### ISSUE TITLE
Can't use spaces in command line arguments

### ISSUE THREAD

**Issue by amw** [vsespb/mt-aws-glacier#86] opened 2014-07-24 23:45 UTC
I've tried various ways of passing a dir path containing spaces on command line and they all failed:

```
mtglacier sync --config=photos.cfg --dir "/dir/with spaces"
mtglacier sync --config=photos.cfg --dir="/dir/with spaces"
mtglacier sync --config=photos.cfg --dir /dir/with\ spaces
mtglacier sync --config=photos.cfg "--dir=/dir/with spaces"
```

Works fine if I declare this in the config file. I'm using OS X 10.9.

**Comment by vsespb** [comment] 2014-07-25 02:14
Hello. I just tried (on Linux however). Runs fine:

```
$ ./mtglacier sync  --config ../glacier.cfg --dir "/tmp/some dir" --vault test1 --journal /tmp/j 
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.115

PID 32395 Started worker
PID 32396 Started worker
PID 32397 Started worker
PID 32398 Started worker
PID 32395 Created an upload_id ZqrDRD7bsyi5MY8GnGpKOPsQu6tsM06onSnd7__60s24CZxl0wu3Sp8mtvqHTdlLUST5auF5lyRMbjyFgkUYdjXbL0ET
PID 32398 Uploaded part for zz at offset [0]
PID 32397 Finished zz hash [4355a46b19d348dc2f57c046f8ef63d4538ebb936000f3c9ee954a27460dd865] archive_id [xDBXi4aWpuUpQMrR3tYkRuse3Z2nsX0Y1Ur8MCycDlFjP5lwu-vcU_5oVz2Yg8M81_8w0KhJCP-kIeHFBvayvRZODIvi5sj92kEjE_DNIOATxYn7JKUkrGQr3Qj39mvtbg6SaO0RvA]
OK DONE
```

according to this topic  http://superuser.com/questions/256985/how-to-cd-to-a-directory-that-contains-a-space-in-its-name OSX quoting should be same.

what error message do you get?

**Comment by amw** [comment] 2014-07-25 02:19
`option "dir" is not a directory`

I've hacked ConfigDefinition.pm around that error to print option value and got my argument without the part starting at space and with the starting `"` included as part of the value (at the beginning).

**Comment by vsespb** [comment] 2014-07-25 02:43
That's all looks related to your shell, not to perl or mtglacier.
Shell is responsible for splitting of command line. Especially if you see `"` in perl script - that just should not be there.

Here is small script for testing

```
#!/usr/bin/env perl
print join(",", map "[$_]", @ARGV);
```

for me it prints

```
./1.pl "hello world"
[hello world]
```

I don't have OSX at all, I can only google how OSX shell works by default and seems it should respect quotes just like mine one.

How that testing script works with spaces for you?

**Comment by amw** [comment] 2014-07-25 02:49
That works fine for me as well.

```
./test.pl "Hello world"
[Hello world]
```

I'm using standard bash in Terminal.app. Quoting arguments and escaping spaces (like `\`) works well with every other script. I will try to add more debug output to that option parsing file tomorrow.

**Comment by vsespb** [comment] 2014-07-25 02:54
> That works fine for me as well.

perl receives it correctly than. I could not imaging how it could be damaged after that (esp. since I cannot reproduce)

Also could you share real name of `/dir/with spaces` ?

**Comment by vsespb** [comment] 2014-07-26 22:02
other things, that could happen

1) parameter passed correctly, but dir indeed does not exists (permissions prob. permissions of parent directory, relative URLS).

2) unicode quotes
http://apple.stackexchange.com/questions/120486/quotes-problem-in-mavericks-or-textedit

3) tilde inside quotes
http://apple.stackexchange.com/questions/108183/open-command-doesnt-like-non-escaped-characters-even-between-quotes

try replace
`validation $_, message('%option a% not a directory'), stop => 1, sub { -d binaryfilename };`
with
`validation $_, message('[%value%] not a directory'), stop => 1, sub { -d binaryfilename };`
for debug.
(ConfigDefinition)

also I need to know exact name of directory.

**Comment by amw** [comment] 2014-07-26 23:18
I think I've got it. It's a problem with the bash script I'm using to run mt-glacier.

This is what does NOT work:

``` bash
GLACIER_OPTS="\
  --config=photos.cfg \
  --dir=\"$DIR_TO_BACKUP\"
  --journal=$JOURNAL \
  --key=$AWS_ID \
  --secret=$AWS_KEY \
  --exclude=.DS_Store"

echo $GLACIER_OPTS
$GLACIER_PATH sync $GLACIER_OPTS --new
```

Output edited to remove my keys:

```
--config=photos.cfg --dir="/var/folders/wc/j9nyb_zn2051zhyfvthtns0c0000gn/T/photo_volume/RAWy Adama" --journal=photos.txt --key=XXXXX --secret=XXXXXX --exclude=.DS_Store
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.115

ERROR: ["/var/folders/wc/j9nyb_zn2051zhyfvthtns0c0000gn/T/photo_volume/RAWy] not a directory
```

This is what works:

``` bash
GLACIER_OPTS="\
  --config=photos.cfg \
  --journal=$JOURNAL \
  --key=$AWS_ID \
  --secret=$AWS_KEY \
  --exclude=.DS_Store"

echo $GLACIER_OPTS
$GLACIER_PATH sync --dir="$DIR_TO_BACKUP" $GLACIER_OPTS --new
```

**Comment by vsespb** [comment] 2014-07-26 23:29
ok, cool. looks like not-a-bug then - closing.

**Closed as completed by vsespb** 2014-07-26 23:29 UTC
Labels: not a bug

**Comment by amw** [comment] 2014-07-26 23:47
Yes, thanks a lot for help. I need to work up my bash skills. There's got to be a way to do it similarly to what I attempted.
