### ISSUE TITLE
Not working on Raspberry pi

### ISSUE THREAD

**Issue by robovergne** [vsespb/mt-aws-glacier#17] opened 2013-01-17 13:17 UTC
Hello.

I've been trying without success to run glacier Backup with mt-aws-glacier. My source directory is just a few scripts gathered for testing.

``` bash
./mtglacier.pl sync --config=/home/pi/glacier.cfg --from-dir /home/pi/test --to-vault=test --journal=/home/pi/journal.log --concurrency=3
```

All threads seems to get stuck on error 500 :

```
PID 2794 HTTP 500 This might be normal. Will retry (11 seconds spent for request)
PID 2793 HTTP 500 This might be normal. Will retry (11 seconds spent for request)
PID 2792 HTTP 500 This might be normal. Will retry (11 seconds spent for request)
```

The unit test fail too :

```
integration/utf8.t ................ ok
integration/metadata.t ............ Dubious, test returned 2 (wstat 512, 0x200)
Failed 188/188 subtests
integration/utf8_line_protocol.t .. ok
integration/journal_readwrite.t ... Dubious, test returned 2 (wstat 512, 0x200)
Failed 580/580 subtests
unit/journal_readjournal.t ........ Dubious, test returned 2 (wstat 512, 0x200)
Failed 31/31 subtests
unit/journal_writejournal.t ....... Dubious, test returned 2 (wstat 512, 0x200)
Failed 3/3 subtests
unit/journal_readfiles.t .......... Dubious, test returned 2 (wstat 512, 0x200)
Failed 26/26 subtests
unit/journal_sanity.t ............. Dubious, test returned 2 (wstat 512, 0x200)
Failed 82/82 subtests
unit/metadata.t ................... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
unit/config_engine_parse.t ........ Dubious, test returned 2 (wstat 512, 0x200)
Failed 33/33 subtests
unit/journal_openmodes.t .......... Dubious, test returned 2 (wstat 512, 0x200)
Failed 16/16 subtests
integration/config_engine_v078.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 178/178 subtests
unit/u_treehash.t ................. ok
integration/journal.t ............. ok
integration/utf8_journal.t ........ ok
integration/t_treehash.t .......... ok

Test Summary Report

integration/metadata.t          (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 188 tests but ran 0.
integration/journal_readwrite.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 580 tests but ran 0.
unit/journal_readjournal.t      (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 31 tests but ran 0.
unit/journal_writejournal.t     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
unit/journal_readfiles.t        (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 26 tests but ran 0.
unit/journal_sanity.t           (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 82 tests but ran 0.
unit/metadata.t                 (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
unit/config_engine_parse.t      (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 33 tests but ran 0.
unit/journal_openmodes.t        (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 16 tests but ran 0.
integration/config_engine_v078.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 178 tests but ran 0.
Files=16, Tests=1234, 58 wallclock secs ( 5.01 usr  0.14 sys + 51.63 cusr  0.88 csys = 57.66 CPU)
Result: FAIL
```

I'm running mt-aws from a raspberry pi (arm computer) under debian wheezy linux.

Any clue about this errors ?

Thank you

**Comment by vsespb** [comment] 2013-01-17 13:38
Hello.

Thanks you for your report and interest in project.

I heard a lot about Raspberry PI, but I don't have it, so I can't reproduce.
I am worrying that it's just runs out of memory..

Let's try to fix it.

1) Are you a perl developer ? Do you have experience installing perl modules via CPAN?
2) how much free memory does R Pi have?
3) When you run testsuite you can get more detailed message by running test directly. i.e. for integration/metadata.t 
you can

```
cd integration
perl metadata.t 
```

4) In the README.md there are required modules/packages for mt-aws-glacier. But for test suite, there are several more packages required. (it's not documented unfortunately as I expect only developers to run test suite). So I think test suite actually failing cause some CPAN modules are missing..

**Comment by vsespb** [comment] 2013-01-17 13:44
Also,
try changing concurrency to concurrency=1 and add partsize=1 (when do real upload, not tes suite).

**Comment by robovergne** [comment] 2013-01-17 13:47
Hi, 
thank you for the prompt answer.

I have written a few perl scripts, but am clearly not a perl developper. I have no experience installing CPAN module, appart from what I have just installed to run MT-AWS
the raspberryPi is indeed very short in memory ; 512 Mb total, and only 115Mb free .

I have try concurency=1, partsize=1, the result is the same : error 500

Here's the output of the metadata test :

```

pi@raspberrypi ~/mt-aws-glacier/t/integration $ perl metadata.t
1..188
Can't locate Test/Deep.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at metadata.t line 27.
BEGIN failed--compilation aborted at metadata.t line 27.
# Looks like your test exited with 2 before it could output anything.
```

missing perl package ? cpan -i Test::Deep ??

**Comment by vsespb** [comment] 2013-01-17 13:58
for glacier sync:

I added a code to print response dump when HTTP 500 happen.

do the following 

```
git checkout development
git pull
```

and re-run 'sync' command. there should be response dump on console with HTTP 500 error explanation..

Also I'll post here instruction how to fix testsuite soon.

**Comment by robovergne** [comment] 2013-01-17 13:58
Ok, i'm in the process of installing perl module to run the tests :

``` bash
sudo cpan -i Test::Deep
sudo cpan -i Test::MockModule
sudo cpan -i Test::DateTime
```

**Comment by robovergne** [comment] 2013-01-17 14:01
Ok, many thank for your reactivity.

Here's the output : 

```
MT-AWS-Glacier, part of MT-AWS suite, Copyright (c) 2012  Victor Efimov http://mt-aws.com/ Version 0.82beta

PID 3716 Started worker
PID 3716 HTTP 500 This might be normal. Will retry (11 seconds spent for request)
500 Can't connect to glacier.eu-west-1 :80 (Bad hostname)
Content-Type: text/plain
Client-Date: Thu, 17 Jan 2013 13:59:51 GMT
Client-Warning: Internal response

Can't connect to glacier.eu-west-1 :80 (Bad hostname)\n
LWP::Protocol::http::Socket: Bad hostname 'glacier.eu-west-1 ' at /usr/share/perl5/LWP/Protocol/http.pm line 51, <GEN3> line 1.\n
PARENT Exit
```

**Comment by vsespb** [comment] 2013-01-17 14:11
1) for testsuite

module list for test suite

```
Test::More Test::Deep Test::MockModule MIME::Base64 DateTime Test::Spec Test::Simple
```

you can install it using "cpan" "cpanp" "cpanm"

I think "cpan" is default tool. But it requires initial configuration.
So I use "cpanp".

And "cpanm" is tools that is very easy to install (minimal dependency etc)

how to install cpanm is described here http://search.cpan.org/dist/App-cpanminus/lib/App/cpanminus.pm

2) HTTP 500 error that I see is pretty strange..

What's your perl version

```
perl -v
```

and lwp::useragent version?

```
perl -MLWP::UserAgent -e 'print $LWP::UserAgent::VERSION; print "\n"'
```

**Comment by vsespb** [comment] 2013-01-17 14:18
Another guess.. maybe your glacier.cfg contains non-linux line feeds (i.e. "\r" or "\r\n" or sth), and this breaks config read code? (error looks like "region" in config contains some strange string..)

**Comment by vsespb** [comment] 2013-01-17 14:29
Also, does this work?:

```
 curl -vv http://glacier.eu-west-1.amazonaws.com/
```

(should return http 400 with Amazon error description.)

**Comment by robovergne** [comment] 2013-01-17 14:35
The perl lib compilation take forever on this smal machine.

Here's the curl output :

```
pi@raspberrypi ~ $  curl -vv http://glacier.eu-west-1.amazonaws.com/
* About to connect() to glacier.eu-west-1.amazonaws.com port 80 (#0)
*   Trying 178.236.6.231...
* connected
* Connected to glacier.eu-west-1.amazonaws.com (178.236.6.231) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.26.0
> Host: glacier.eu-west-1.amazonaws.com
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 400 Bad Request
< x-amzn-RequestId: fP5SVEX2VhhbrCuoHd-g7yZxkLDuGra7EUcIKsGKlMLW5IY
< Content-Length: 109
< Date: Thu, 17 Jan 2013 14:30:36 GMT
<
* Connection #0 to host glacier.eu-west-1.amazonaws.com left intact
{"code":"MissingParameterValueException","message":"Required parameter missing:                                          API version","type":"Client"}* Closing connection #0
```

ANDDDDDDDDD

```
cat glacier.cfg> temp && cat temp>glacier.cfg
```

seems to have solved the problem. Seems you were right : there must be a parsing problem of the cfg file.

Thank you very much for your help.

**Comment by vsespb** [comment] 2013-01-17 14:41
Ok. Cool.

Do you have original glacier.cfg? ;)

I've tried to break my code.. seems it works fine with Window CR/LF format but simply not works with Mac OS _Classic_ format..

How (using what software did you create that file) ?

Also could you paste it here (original file or at least fixed file) ? (of course need to replace secret key characters with *)

**Comment by robovergne** [comment] 2013-01-17 14:49
I have the original cfg file. I cannot paste it here because it is on a remote server, but i can email it to you later.
It was created by pasting the code from the git main page of the project into vim, through a SSH connection established with putty.
Also maybe worth mention that the system locale is FR_Fr (utf8 I think)

**Comment by vsespb** [comment] 2013-01-17 14:54
Ok, would be great if you can send it to me ( vs [at] vs-dev.com).
I'll try to do something to avoid this situation in the future (maybe fix code or main project page).

Meanwhile I am closing the issue.
Thanks!

**Closed as completed by vsespb** 2013-01-17 14:54 UTC
Labels: bug, deploy_issue
