### ISSUE TITLE
Exit with SIGCHLD

### ISSUE THREAD

**Issue by ihartley-zz** [vsespb/mt-aws-glacier#54] opened 2013-12-07 15:09 UTC
Hi, 

Fantastic work!!  I hope Google are paying you lots!! :-)

Am using 1.059, Perl 5.10 on a QNAP NAS.  It's an ARM so no very powerful, and have reduced concurrency to 2 and partsize to 8MB (on a 3Mb/s upload connection).

The sync fails with SIGCHLD (returned from a shell script) before completion every 100s/1000s files - when I restart it just carries on as normal.  Sometimes there are 400/408 errors, sometimes not.  How can I get more detailed info regarding what is causing this issue??

Have recommended your software on QNAP fourms!

Thanks, H.

**Comment by vsespb** [comment] 2013-12-07 15:12
Hi. Thank you for feedback and recommendations.

SIGCHLD means some of child processes terminated with exception (meaning, probably, that exception related to network operations).

I need full program output to tell more. If you running it from bash script, try redirect STDOUT and STDERR to log files.

**Comment by ihartley-zz** [comment] 2013-12-07 15:20
My goodness - what a fast reply, thanks!  Please, in future, do like professional support teams and wait 3 days before replying :-)  (English humour)

I'm guessing I don't see the output because it's via /bin/sh.  Will redirect and get back to you with more info.  Thanks again, H.

On Saturday, 7 December 2013, 15:12, Victor Efimov notifications@github.com wrote:

Hi. Thank you for feedback and recommendations.

**Comment by vsespb** [comment] 2013-12-07 15:21
Ok.

`Exit with SIGCHLD` is the last message before termination, but there should be another one (stacktrace and error message), right before `Exit with SIGCHLD`.

If there are no other messages - check `/var/log/syslog` for things like out of memory/OOM killer.

**Comment by vsespb** [comment] 2013-12-10 20:02
let's close if as duplicate of #55 as we started investigation of SIGCHLD in it.

**Closed as completed by vsespb** 2013-12-10 20:02 UTC
Labels: duplicate

**Comment by ihartley-zz** [comment] 2013-12-11 13:08
To check, I changed my upload speed from 3Mb to 12Mb (very expensive!).  The upload speed stays the same, and goes up and down x2 if I change the partsize x2.

Must be software....

On Tuesday, 10 December 2013, 20:02, Victor Efimov notifications@github.com wrote:

Closed #54.

**Comment by vsespb** [comment] 2013-12-11 17:42
> I changed my upload speed from 3Mb to 12Mb (very expensive!).  The upload speed stays the same

that means you didn't change the speed actually?

anyway this ticket is closed lets continue in # 55
